### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by lorond** [ritchiecarroll/Report.NET#1]
Does not handle encoding well.
For example (`Тестовая строка` - it's `Text string` in Russian), instead of:
![correct encoding](https://cloud.githubusercontent.com/assets/1833263/14672200/03b3ab78-06ff-11e6-901c-1e883c776f33.PNG)

library generates:
![incorrect encoding](https://cloud.githubusercontent.com/assets/1833263/14672232/336405fc-06ff-11e6-8445-246a72ebef7e.PNG)

**Comment by lorond** [comment]
public class TestReport : Report
    {
        protected override void Create()
        {
            var font = new FontDef(this, FontDef.StandardFont.TimesRoman);
            var font_title = new FontPropMM(font, 5);
            new Page(this);
            this.page_Cur.AddAlignedMM(30, RepObj.rAlignLeft, 30, RepObj.rAlignTop, new RepString(font_title, "Тестовая строка"));
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var r = new TestReport();
            r.Save("test.pdf");
        }
    }

**Comment by ritchiecarroll** [comment]
Just a thought: maybe the selected/default font doesn't include the Russian letters? Have you tried changing the font for the text?

**Comment by ritchiecarroll** [comment]
Here's what we have discovered about this library: Report.NET, by default, uses the standard AFM fonts that are expected to be supported by all PDF readers. These fonts do not not support high-order Unicode characters. There is, however, a function that you can use to assign / embed a true-type font for the PDF to use - in our experimentation this did work, but the text metric calculations were off - at least in our converted test case. I suggest you try this method and see if it works better for with Russian alphabet.
