### ISSUE TITLE
page size

### ISSUE THREAD

**Issue by bidplayrepeat** [ritchiecarroll/Report.NET#11]
Is there a way to state a page size. viz. A4, A3 etc. since by default it takes A4 - i found some come code in the source but did not find how it can be used

**Comment by bidplayrepeat** [comment]
Ah, that means I have to specify the page size for each page created, not for the entire report. OK. 

Also just wanted to know if there any limit to the size of PDF it can generate. No of pages, No of MB/GB etc. Or it will just keep on writing to disk - if the report lets say contains thousands of pages.

**Comment by ritchiecarroll** [comment]
No built-in limits, as far as I am aware - we have created reports with 10s of pages, never thousands, but I suspect it will work fine.

You'll want to experiment for sure, watch memory usage, etc.

**Comment by bidplayrepeat** [comment]
Thanks a Lot. Will contact you incase I require some other clarifications. 

Aside : 
1. There seem to be a lot of duplication in terms of normal method names viz. method and methodMM.  May be the MethodMM can be the only public and plain once made private. 

2. What is the main difference between ListLayout and Tablelayout - I have not found a major programmatic difference between the two. I have not been able to think of a specific case where TableLayout MUST BE USED & ListLayout CAN NOT BE USED.  

Thanks for feedback.

One doubt - Is it possible to have two Containers on a single page ? of varying heights & widths.

**Comment by ritchiecarroll** [comment]
I didn't write the code, this project is a fork from VERY old code from SourceForge. The main reason for this fork was (1) to produce NuGet packages, and (2) fix some bugs.

So really I just "use" the code - outside fixing a few bugs, I've never made an attempt to "improve" anything - as a result, the code "is what is is" in terms of quality and functionality.

I have reviewed the code, so I am comfortable with using it, and it does its job...

Thanks,
Ritchie

**Comment by bidplayrepeat** [comment]
Yes. True, I had used this project way back  successfully. (about 15 years ago) but unfortunetly my code was lost. Now a need has arisen again.  :-( . Lets see. Anyway, thanks for the feedback.

**Comment by ritchiecarroll** [comment]
If it's of any value, as an example, here's the tool we have developed that uses the library:
https://github.com/GridProtectionAlliance/gsf/tree/master/Source/Tools/StatHistorianReportGenerator
